sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root123&&
  wechat:
    appid: wx4e9f439931b8e4b8
    secret: 77adebaa4f689148f6db5de5722a0eef
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9ztVacMu6EY2XSe9N3
    access-key-secret: EvEHE3Zm7taRP0tl3g5edzpuHsBV10
    bucket-name: sky-itcast-fjyy2
  redis:
    host: localhost
    port: 6379
    password: foobared
    database: 0



