sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root123&&
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9ztVacMu6EY2XSe9N3
    access-key-secret: EvEHE3Zm7taRP0tl3g5edzpuHsBV10
    bucket-name: sky-itcast-fjyy2



